Начиная с версии 1.13, Go даёт возможность «упаковывать», или «обёртывать», ошибки (**wrapping error**). Это означает, что можно создавать новую ошибку поверх старой, но сохранять возможность восстановить оригинальную ошибку. Это может понадобиться для создания собственных типов ошибок на основе уже существующих. Ниже приводится пример.

![image](https://pictures.s3.yandex.net:443/resources/6.1.wrapping_1643209004.png)

Вспомните пример с чтением файла конфигурации, где происходит замена одной ошибки на другую. Текст оригинальной ошибки остаётся, но восстановить её тип невозможно. Чтобы обернуть ошибку, нужно использовать спецификатор `%w` для функции `Errorf`.


Если вместо `fmt.Errorf()` мы захотим использовать собственный тип ошибки — дело усложнится. Допустим, хотим записывать в ошибку название языка отдельным полем:

```go
type languageErr struct {
    lang string
}

func (le languageErr) Error() string {
    return fmt.Sprintf("%s language error", le.lang)
}
```

Чтобы `languageErr` могла выступать оберткой для других ошибок, придется сделать еще две вещи:

1.  Добавить отдельное поле для внутренней ошибки (ее будем оборачивать).
2.  Добавить метод `Unwrap()`, который возвращает внутреннюю ошибку («разворачивает»).

```go
type languageErr struct {
    lang string
    err  error
}

func (le languageErr) Error() string {
    return fmt.Sprintf("%s language error: %v", le.lang, le.err)
}

func (le languageErr) Unwrap() error {
    return le.err
}
```

Теперь можно создать новую `languageErr` как обертку над исходной ошибкой в методе `describe()`:

```go
func (l languages) describe(lang string) (string, error) {
    descr, err := getValue(l, lang)
    if err != nil {
        return "", languageErr{lang, err}
    }
    return descr, nil
}
```

Сама по себе слоеная ошибка — только половина дела. Вторая половина — научиться клиенту с ней работать. Сейчас посмотрим, как.

### errors.Is()

Получив ошибку-матрешку, клиент может проверить, есть ли на каком-то слое интересующая его проблема. Для этого используют функцию `errors.Is()`:

```go
func (l languages) describe(lang string) (string, error) {
    descr, err := getValue(l, lang)
    if err != nil {
        return "", languageErr{lang, err}
    }
    return descr, nil
}

// ...

func main() {
    descr, err := langs.describe("java")
    if errors.Is(err, errNotFound) {
        fmt.Println("this is an errNotFound error")
        // do something about it...
    }
    if err != nil {
        fmt.Println(err)
        return
    }
    fmt.Println(descr)
}
```

```bash
this is an errNotFound error
java language error: not found
```

Неважно, сколько в ошибке слоев. Если на каком-то из них встретилось значение `errNotFound` — `errors.Is()` вернет `true`.

[песочница](https://go.dev/play/p/bX5LaSSHHQa)

### errors.As()

Раньше мы использовали приведение типа, чтобы получить доступ к ошибке конкретного типа вместо абстрактного `error`:

```go
descr, err := langs.describe("java")
if langErr, ok := err.(languageErr); ok {
    fmt.Println("Language error:", langErr.lang)
}
```

```no-highlight
Language error: java
```

Но это работает только для ошибки самого верхнего уровня. До ошибки из середины «матрешки» через приведение типа не добраться. А вот через `errors.As()` — можно:

```go
descr, err := langs.describe("java")
// обернем еще раз, чтобы languageErr
// оказалась внутрь матрешки
err = fmt.Errorf("wrap once more: %w", err)

var langErr languageErr
if errors.As(err, &langErr) {
    fmt.Println("Language error:", langErr.lang)
}
```

```no-highlight
Language error: java
wrap once more: java language error: not found
```

`errors.As()` проверяет каждый слой ошибки, и если видит там искомый тип `languageErr` — заполняет значение `langErr` по переданному указателю, и возвращает `true`. Если искомого типа нет — возвращает `false`.

[песочница](https://go.dev/play/p/mDY0C-7E32A)

Итого по обертыванию:

-   Простой способ создать новую ошибку на основе существующей — `fmt.Errorf()` и спецификатор `%w`
-   Если нужен собственный тип ошибки, придется добавить в него поле типа `error` и метод `Unwrap()`
-   `errors.Is()` проверяет конкретную ошибку на каждом слое.
-   `errors.As()` заполняет ошибку конкретного типа, если он встречается на одном из слоев.

Исправим `%v` на `%w` в функции `ReadTextFile`:

```go
func ReadTextFile(filename string) (string, error) {
    data, err := os.ReadFile(filename)
    if err != nil {
        // возвратим ошибку на русском языке
        return "", fmt.Errorf(`не удалось прочитать файл (%s): %w`, filename, err)
    }
    return string(data), nil
} 
```

В этом случае можно восстановить оригинальную ошибку, используя функцию `errors.Unwrap`, и добавить дополнительные проверки.

Кроме того, в пакете `github.com/pkg/errors` есть функции `Wrap` и `Wrapf`, которые создают обёрнутую ошибку.

Для чего нужно оборачивать ошибки? Дело в том, что с помощью обёртывания можно создать некоторую иерархию ошибок:

```go
// Статически создаём ошибку.
var ErrFileReading = errors.New("read_text_file: read file error") 

func ReadTextFileByName(filename string) (string, error) {
    if data, err := os.ReadFile(filename); err != nil {
        // будет вызван метод 'Error() string', который преобразует ошибку в строку
        fmt.Println(err)
        return errors.Wrapf(ErrFileReading, "file not exist %s", filename)
    }   
    fmt.Println(string(data))
    return string(data), nil
} 
```

А теперь в месте вызова нашей функции сравним:

```go
if errors.Is(err, ErrFileReading) {
    // что-то делаем
    
} 
```

Функция `Is` сравнивает ошибки, причём даже обёрнутые! Благодаря этому можно обрабатывать обёрнутые ошибки и передавать в них какую-то дополнительную информацию.

Хорошим тоном для архитектуры считается, чтобы пакет возвращал только свои ошибки. Набор ошибок пакета является частью контракта по работе с ним. Пробрасывая полученные ошибки из других пакетов, увеличиваем связность пакетов. Ведь тогда стороне, обрабатывающей ошибки, придётся обрабатывать не только ошибки нашего пакета, но и пакетов, от которых зависим.

[[Ошибки]] [[Собственный тип ошибки]]
